name: EssentialFeed

############
# Options
############

options:
  bundleIdPrefix: com.jill.app
  xcodeVersion: "13.2.1"
  deploymentTarget:
    iOS: 13.0

############
# Configs
############

# configs:
#   Debug: debug
#   Release: release
#   Adhoc: release
#   Beta: release    

############
# Packages
############

# packages:
#   Quick:
#     url: https://github.com/Quick/Quick.git
#     majorVersion: 5.0.0

#   Nimble:
#     url: https://github.com/Quick/Nimble.git
#     majorVersion: 10.0.0


############
# Schemes
############

schemes: 
  EssentialFeed:
    build:
      targets:
        EssentialFeed: all         
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - EssentialFeed
      targets:  
        - name: EssentialFeedTests 
          randomExecutionOrder: true  
    profile: 
      config: Debug 
    analyze:
      config: Debug
    archive: 
      config: Debug

############
# Targets
############

targets:

  # -----------
  # EssentialFeed
  # -----------

  EssentialFeed:
    type: application   
    platform: iOS
    
    # sources 
    sources: 
      - path: EssentialFeed 

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: EssentialFeed/Info.plist
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64

  # -----------
  # EssentialFeedAPIEndToEndTests
  # -----------

  EssentialFeedAPIEndToEndTests:
    type: bundle.unit-test
    platform: iOS

    # sources
    sources:
      - EssentialFeedAPIEndToEndTests

    # dependencies
    dependencies:
      - target: EssentialFeed
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: EssentialFeedAPIEndToEndTests/Info.plist
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64

  # -----------
  # EssentialFeedTests
  # -----------

  EssentialFeedTests:
    type: bundle.unit-test
    platform: iOS

    # sources
    sources:
      - EssentialFeedTests

    # dependencies
    dependencies:
      - target: EssentialFeed
    #   - package: Quick
    #   - package: Nimble
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: EssentialFeedTests/Info.plist
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64